# Generated by Selenium IDE (adaptado a infraestructura común)
import time

from selenium.webdriver.common.by import By

from core.environment.host import get_host_for_selenium_testing
from core.selenium.common import close_driver, initialize_driver


def test_selenium_following_and_communities():
    driver = initialize_driver()

    try:
        host = get_host_for_selenium_testing()

        # Inicio
        driver.get(f"{host}/")
        driver.set_window_size(1332, 965)

        # Login
        driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        driver.find_element(By.ID, "email").click()
        driver.find_element(By.ID, "password").send_keys("1234")
        driver.find_element(By.ID, "email").send_keys("user1@example.com")
        driver.find_element(By.ID, "submit").click()

        # Ir a Following
        driver.find_element(By.LINK_TEXT, "Following").click()
        driver.find_element(By.CSS_SELECTOR, ".card-body").click()
        driver.find_element(By.NAME, "q").click()
        driver.find_element(By.NAME, "q").send_keys("user")
        driver.find_element(By.CSS_SELECTOR, ".btn").click()
        driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
        driver.find_element(By.CSS_SELECTOR, ".btn-outline-danger").click()

        # Ir a Communities
        driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(5) .align-middle:nth-child(2)").click()
        driver.find_element(By.ID, "createCommunityBtn").click()
        driver.find_element(By.NAME, "name").click()
        driver.find_element(By.NAME, "name").send_keys("pruebadef")
        driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3) .form-control").click()
        driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3) .form-control").send_keys("aaa")
        driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(1)").click()

        # Volver a Following y gestionar la comunidad
        driver.find_element(By.LINK_TEXT, "Following").click()
        driver.find_element(By.NAME, "q").click()
        driver.find_element(By.NAME, "q").send_keys("pruebadef")
        driver.find_element(By.CSS_SELECTOR, ".btn").click()
        driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
        driver.find_element(By.CSS_SELECTOR, ".btn-outline-danger").click()

        # Logout
        driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
        driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(2)").click()

        time.sleep(2)

    finally:
        close_driver(driver)
