# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestProfile2fa():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()
             
    def test_profile2fa(self):
        self.driver.get("http://127.0.0.1:5000/login?next=%2Fprofile%2Fedit")
        self.driver.set_window_size(1400, 861)
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(9) .align-middle:nth-child(2)").click()
        self.driver.find_element(By.LINK_TEXT, "Enable 2FA").click()
        self.driver.find_element(By.NAME, "verification_code").send_keys("111111")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-success:nth-child(2)").click()
        self.driver.find_element(By.LINK_TEXT, "Cancel").click()
        self.driver.find_element(By.CSS_SELECTOR, ".content").click()
      
