services:

  web:
    container_name: web_app_container
    image: <your_dockerhub_name>/uvlhub:latest
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./entrypoints/production_entrypoint.sh:/app/entrypoint.sh
      - ../scripts:/app/scripts
      - ../migrations:/app/migrations
      - ../uploads:/app/uploads
      - ../.moduleignore:/app/.moduleignore
    command: [ "sh", "-c", "sh /app/entrypoint.sh" ]

  db:
    container_name: mariadb_container
    env_file:
      - ../.env
    image: mariadb:12.0.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: nginx_web_server_container
    image: nginx:1.29.1
    volumes:
      - ./nginx/nginx.prod.ssl.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./public:/var/www:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always

  watchtower:
    container_name: watchtower_container
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 120 web_app_container
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    volumes:
      - ./public:/var/www:rw
      - ./letsencrypt:/etc/letsencrypt

volumes:
  db_data:
