"""empty message

Revision ID: 001
Revises:
Create Date: 2025-12-14 11:18:52.409945

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("visual_identity", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "dataset_concept",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conceptual_doi", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conceptual_doi"),
    )
    op.create_table(
        "doi_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_doi_old", sa.String(length=120), nullable=True),
        sa.Column("dataset_doi_new", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ds_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number_of_models", sa.String(length=120), nullable=True),
        sa.Column("number_of_features", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fakenodo_deposition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conceptrecid", sa.String(length=120), nullable=False),
        sa.Column("conceptdoi", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=True),
        sa.Column("dirty", sa.Boolean(), nullable=True),
        sa.Column("doi", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conceptdoi"),
    )
    op.create_table(
        "fm_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("solver", sa.Text(), nullable=True),
        sa.Column("not_solver", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("otp_secret", sa.String(length=100), nullable=True),
        sa.Column("twofa_enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table("webhook", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_table(
        "community_curators",
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("community_id", "user_id"),
    )
    op.create_table(
        "ds_meta_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deposition_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "publication_type",
            sa.Enum("NONE", "REGIONAL", "NATIONAL", "CONTINENTAL", "OTHER", name="publicationtype"),
            nullable=False,
        ),
        sa.Column("publication_doi", sa.String(length=120), nullable=True),
        sa.Column("dataset_doi", sa.String(length=120), nullable=True),
        sa.Column("tags", sa.String(length=120), nullable=True),
        sa.Column("ds_metrics_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ds_metrics_id"],
            ["ds_metrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fakenodo_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(length=120), nullable=False),
        sa.Column("deposition_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deposition_id"],
            ["fakenodo_deposition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id"),
    )
    op.create_table(
        "fakenodo_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deposition_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("doi", sa.String(length=120), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("files_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deposition_id"],
            ["fakenodo_deposition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
    )
    op.create_table(
        "fm_meta_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "publication_type",
            sa.Enum("NONE", "REGIONAL", "NATIONAL", "CONTINENTAL", "OTHER", name="publicationtype"),
            nullable=False,
        ),
        sa.Column("publication_doi", sa.String(length=120), nullable=True),
        sa.Column("tags", sa.String(length=120), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=True),
        sa.Column("fm_metrics_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fm_metrics_id"],
            ["fm_metrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_author_follow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("follower_id", "author_id", name="uq_user_author_follow"),
    )
    op.create_table(
        "user_community_follow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "community_id", name="uq_user_community_follow"),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("orcid", sa.String(length=19), nullable=True),
        sa.Column("affiliation", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "user_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("device_info", sa.String(length=256), nullable=True),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_activity", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_session_session_id"), ["session_id"], unique=True)

    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("affiliation", sa.String(length=120), nullable=True),
        sa.Column("orcid", sa.String(length=120), nullable=True),
        sa.Column("ds_meta_data_id", sa.Integer(), nullable=True),
        sa.Column("fm_meta_data_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ds_meta_data_id"],
            ["ds_meta_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fm_meta_data_id"],
            ["fm_meta_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ds_meta_data_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("ds_concept_id", sa.Integer(), nullable=True),
        sa.Column("version_number", sa.String(length=64), nullable=True),
        sa.Column("is_latest", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ds_concept_id"],
            ["dataset_concept.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ds_meta_data_id"],
            ["ds_meta_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ds_meta_data_edit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ds_meta_data_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=False),
        sa.Column("field_name", sa.String(length=50), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("change_summary", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["ds_meta_data_id"],
            ["ds_meta_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "community_dataset_proposal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("proposed_by", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataset_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ds_download_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("dataset_id", sa.Integer(), nullable=True),
        sa.Column("download_date", sa.DateTime(), nullable=False),
        sa.Column("download_cookie", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ds_view_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("dataset_id", sa.Integer(), nullable=True),
        sa.Column("view_date", sa.DateTime(), nullable=False),
        sa.Column("view_cookie", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feature_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data_set_id", sa.Integer(), nullable=False),
        sa.Column("fm_meta_data_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_set_id"],
            ["data_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fm_meta_data_id"],
            ["fm_meta_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("checksum", sa.String(length=120), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("feature_model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_model_id"],
            ["feature_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_download_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("download_date", sa.DateTime(), nullable=False),
        sa.Column("download_cookie", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_view_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("view_date", sa.DateTime(), nullable=True),
        sa.Column("view_cookie", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_view_record")
    op.drop_table("file_download_record")
    op.drop_table("file")
    op.drop_table("feature_model")
    op.drop_table("ds_view_record")
    op.drop_table("ds_download_record")
    op.drop_table("dataset_comment")
    op.drop_table("community_dataset_proposal")
    op.drop_table("comment")
    op.drop_table("ds_meta_data_edit_log")
    op.drop_table("data_set")
    op.drop_table("author")
    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_session_session_id"))

    op.drop_table("user_session")
    op.drop_table("user_roles")
    op.drop_table("user_profile")
    op.drop_table("user_community_follow")
    op.drop_table("user_author_follow")
    op.drop_table("fm_meta_data")
    op.drop_table("fakenodo_version")
    op.drop_table("fakenodo_file")
    op.drop_table("ds_meta_data")
    op.drop_table("community_curators")
    op.drop_table("webhook")
    op.drop_table("user")
    op.drop_table("role")
    op.drop_table("fm_metrics")
    op.drop_table("fakenodo_deposition")
    op.drop_table("ds_metrics")
    op.drop_table("doi_mapping")
    op.drop_table("dataset_concept")
    op.drop_table("community")
    # ### end Alembic commands ###
