"""first migration (combined)

Revision ID: 001
Revises:
Create Date: 2024-09-08 16:50:20.326640

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doi_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_doi_old", sa.String(length=120), nullable=True),
        sa.Column("dataset_doi_new", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ds_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number_of_models", sa.String(length=120), nullable=True),
        sa.Column("number_of_features", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fm_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("solver", sa.Text(), nullable=True),
        sa.Column("not_solver", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Tabla añadida de la segunda migración (creada aquí para la FK de data_set)
    op.create_table(
        "dataset_concept",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conceptual_doi", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conceptual_doi"),
    )

    # Tabla 'user' con modificaciones de la segunda migración aplicadas
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("otp_secret", sa.String(length=32), nullable=True),
        sa.Column(
            "twofa_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "webhook",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "zenodo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ds_meta_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deposition_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "publication_type",
            sa.Enum(
                "NONE",
                "REGIONAL",
                "NATIONAL",
                "CONTINENTAL",
                "OTHER",
                name="publicationtype",
            ),
            nullable=False,
        ),
        sa.Column("publication_doi", sa.String(length=120), nullable=True),
        sa.Column("dataset_doi", sa.String(length=120), nullable=True),
        sa.Column("tags", sa.String(length=120), nullable=True),
        sa.Column("ds_metrics_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ds_metrics_id"],
            ["ds_metrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fm_meta_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "publication_type",
            sa.Enum(
                "NONE",
                "REGIONAL",
                "NATIONAL",
                "CONTINENTAL",
                "OTHER",
                name="publicationtype",
            ),
            nullable=False,
        ),
        sa.Column("publication_doi", sa.String(length=120), nullable=True),
        sa.Column("tags", sa.String(length=120), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=True),
        sa.Column("fm_metrics_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fm_metrics_id"],
            ["fm_metrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("orcid", sa.String(length=19), nullable=True),
        sa.Column("affiliation", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("affiliation", sa.String(length=120), nullable=True),
        sa.Column("orcid", sa.String(length=120), nullable=True),
        sa.Column("ds_meta_data_id", sa.Integer(), nullable=True),
        sa.Column("fm_meta_data_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ds_meta_data_id"],
            ["ds_meta_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fm_meta_data_id"],
            ["fm_meta_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Tabla 'data_set' con modificaciones de la segunda migración aplicadas
    op.create_table(
        "data_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ds_meta_data_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ds_meta_data_id"],
            ["ds_meta_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        # FK añadida de la segunda migración
        sa.ForeignKeyConstraint(
            ["ds_concept_id"],
            ["dataset_concept.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ds_download_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("dataset_id", sa.Integer(), nullable=True),
        sa.Column("download_date", sa.DateTime(), nullable=False),
        sa.Column("download_cookie", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ds_view_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("dataset_id", sa.Integer(), nullable=True),
        sa.Column("view_date", sa.DateTime(), nullable=False),
        sa.Column("view_cookie", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["data_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feature_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data_set_id", sa.Integer(), nullable=False),
        sa.Column("fm_meta_data_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_set_id"],
            ["data_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fm_meta_data_id"],
            ["fm_meta_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("checksum", sa.String(length=120), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("feature_model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_model_id"],
            ["feature_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_download_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("download_date", sa.DateTime(), nullable=False),
        sa.Column("download_cookie", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_view_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("view_date", sa.DateTime(), nullable=True),
        sa.Column("view_cookie", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=50), nullable=False, unique=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("dataset_id", sa.Integer, nullable=False),
        sa.Column("author_id", sa.Integer, nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime,
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "approved",
            sa.Boolean,
            nullable=True,
            server_default=sa.false(),
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["data_set.id"]),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"]),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # use IF EXISTS so downgrade is tolerant if some tables are already missing
    op.execute("DROP TABLE IF EXISTS `comment`")
    op.execute("DROP TABLE IF EXISTS `file_view_record`")
    op.execute("DROP TABLE IF EXISTS `file_download_record`")
    op.execute("DROP TABLE IF EXISTS `file`")
    op.execute("DROP TABLE IF EXISTS `feature_model`")
    op.execute("DROP TABLE IF EXISTS `ds_view_record`")
    op.execute("DROP TABLE IF EXISTS `ds_download_record`")
    op.execute("DROP TABLE IF EXISTS `data_set`")
    op.execute("DROP TABLE IF EXISTS `author`")
    op.execute("DROP TABLE IF EXISTS `user_profile`")
    op.execute("DROP TABLE IF EXISTS `fm_meta_data`")
    op.execute("DROP TABLE IF EXISTS `ds_meta_data`")
    op.execute("DROP TABLE IF EXISTS `zenodo`")
    # webhook no existe, así que no se borra
    op.execute("DROP TABLE IF EXISTS `fm_metrics`")
    op.execute("DROP TABLE IF EXISTS `ds_metrics`")
    op.execute("DROP TABLE IF EXISTS `doi_mapping`")
    op.execute("DROP TABLE IF EXISTS `user_roles`")
    op.execute("DROP TABLE IF EXISTS `role`")
    op.execute("DROP TABLE IF EXISTS `user`")
    op.execute("DROP TABLE IF EXISTS `dataset_concept`")
    # ### end Alembic commands ###
