"""add follow tables

Revision ID: 485dc55cc680
Revises: 006_add_user_sessions
Create Date: 2025-12-03 21:01:56.572568

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "485dc55cc680"
down_revision = "006_add_user_sessions"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_author_follow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("follower_id", "author_id", name="uq_user_author_follow"),
    )
    op.create_table(
        "user_community_follow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "community_id", name="uq_user_community_follow"),
    )
    op.drop_table("webhook")
    with op.batch_alter_table("data_set", schema=None) as batch_op:
        batch_op.alter_column(
            "dataset_type", existing_type=mysql.VARCHAR(length=120), type_=sa.String(length=50), nullable=False
        )
        batch_op.alter_column(
            "storage_path",
            existing_type=mysql.VARCHAR(length=255),
            type_=sa.String(length=1024),
            existing_nullable=True,
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "otp_secret", existing_type=mysql.VARCHAR(length=32), type_=sa.String(length=16), existing_nullable=True
        )
        batch_op.alter_column(
            "twofa_enabled",
            existing_type=mysql.TINYINT(display_width=1),
            nullable=True,
            existing_server_default=sa.text("0"),
        )

    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("session_id"))
        batch_op.drop_index(batch_op.f("ix_user_session_session_id"))
        batch_op.create_index(batch_op.f("ix_user_session_session_id"), ["session_id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_session_session_id"))
        batch_op.create_index(batch_op.f("ix_user_session_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("session_id"), ["session_id"], unique=True)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "twofa_enabled",
            existing_type=mysql.TINYINT(display_width=1),
            nullable=False,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "otp_secret", existing_type=sa.String(length=16), type_=mysql.VARCHAR(length=32), existing_nullable=True
        )

    with op.batch_alter_table("data_set", schema=None) as batch_op:
        batch_op.alter_column(
            "storage_path",
            existing_type=sa.String(length=1024),
            type_=mysql.VARCHAR(length=255),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "dataset_type", existing_type=sa.String(length=50), type_=mysql.VARCHAR(length=120), nullable=True
        )

    op.create_table(
        "webhook",
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("user_community_follow")
    op.drop_table("user_author_follow")
    # ### end Alembic commands ###
