"""empty message

Revision ID: 011_add_fakenodo_versions
Revises: 010_add_dataset_comments
Create Date: 2025-12-13 01:50:13.126747

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "011_add_fakenodo_versions"
down_revision = "010_add_dataset_comments"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table("dataset_concept"):
        op.create_table(
            "dataset_concept",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("conceptual_doi", sa.String(length=120), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("conceptual_doi"),
        )
    if not inspector.has_table("comment"):
        op.create_table(
            "comment",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("dataset_id", sa.Integer(), nullable=False),
            sa.Column("author_id", sa.Integer(), nullable=False),
            sa.Column("content", sa.Text(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("approved", sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(
                ["author_id"],
                ["user.id"],
            ),
            sa.ForeignKeyConstraint(
                ["dataset_id"],
                ["data_set.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    with op.batch_alter_table("data_set", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ds_concept_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("version_number", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("is_latest", sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, "dataset_concept", ["ds_concept_id"], ["id"])
        batch_op.drop_column("dataset_type")
        batch_op.drop_column("storage_path")

    with op.batch_alter_table("dataset_comment", schema=None) as batch_op:
        # Drop foreign key constraints first to allow dropping indexes in MySQL
        # There may be multiple FK constraints (one for dataset_id and one for user_id).
        try:
            batch_op.drop_constraint(batch_op.f("dataset_comment_ibfk_1"), type_="foreignkey")
        except Exception:
            pass
        try:
            batch_op.drop_constraint(batch_op.f("dataset_comment_ibfk_2"), type_="foreignkey")
        except Exception:
            pass
        batch_op.drop_index(batch_op.f("ix_dataset_comment_created_at"))
        batch_op.drop_index(batch_op.f("ix_dataset_comment_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_dataset_comment_user_id"))
        # Recreate foreign key referencing the updated table
        batch_op.create_foreign_key(None, "data_set", ["dataset_id"], ["id"])

    with op.batch_alter_table("ds_meta_data_edit_log", schema=None) as batch_op:
        # Drop foreign key constraints first to allow dropping indexes in MySQL
        try:
            batch_op.drop_constraint(batch_op.f("ds_meta_data_edit_log_ibfk_1"), type_="foreignkey")
        except Exception:
            pass
        try:
            batch_op.drop_constraint(batch_op.f("ds_meta_data_edit_log_ibfk_2"), type_="foreignkey")
        except Exception:
            pass
        batch_op.drop_index(batch_op.f("ix_ds_meta_data_edit_log_ds_meta_data_id"))
        batch_op.drop_index(batch_op.f("ix_ds_meta_data_edit_log_edited_at"))

    with op.batch_alter_table("fakenodo_deposition", schema=None) as batch_op:
        batch_op.add_column(sa.Column("conceptdoi", sa.String(length=120), nullable=False))
        batch_op.alter_column(
            "conceptrecid",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.String(length=120),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "published",
            existing_type=mysql.TINYINT(display_width=1),
            nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "dirty", existing_type=mysql.TINYINT(display_width=1), nullable=True, existing_server_default=sa.text("0")
        )
        batch_op.create_unique_constraint(None, ["conceptdoi"])

    with op.batch_alter_table("fakenodo_file", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fakenodo_file_ibfk_1"), type_="foreignkey")
        batch_op.create_foreign_key(None, "fakenodo_deposition", ["deposition_id"], ["id"])

    with op.batch_alter_table("fakenodo_version", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fakenodo_version_ibfk_1"), type_="foreignkey")
        batch_op.create_foreign_key(None, "fakenodo_deposition", ["deposition_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fakenodo_version", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fakenodo_version_ibfk_1"), "fakenodo_deposition", ["deposition_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("fakenodo_file", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fakenodo_file_ibfk_1"), "fakenodo_deposition", ["deposition_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("fakenodo_deposition", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "dirty", existing_type=mysql.TINYINT(display_width=1), nullable=False, existing_server_default=sa.text("0")
        )
        batch_op.alter_column(
            "published",
            existing_type=mysql.TINYINT(display_width=1),
            nullable=False,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "conceptrecid",
            existing_type=sa.String(length=120),
            type_=mysql.INTEGER(display_width=11),
            existing_nullable=False,
        )
        batch_op.drop_column("conceptdoi")

    with op.batch_alter_table("ds_meta_data_edit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ds_meta_data_edit_log_edited_at"), ["edited_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ds_meta_data_edit_log_ds_meta_data_id"), ["ds_meta_data_id"], unique=False)

    with op.batch_alter_table("dataset_comment", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("dataset_comment_ibfk_1"), "data_set", ["dataset_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_index(batch_op.f("ix_dataset_comment_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dataset_comment_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dataset_comment_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("data_set", schema=None) as batch_op:
        batch_op.add_column(sa.Column("storage_path", mysql.VARCHAR(length=1024), nullable=True))
        batch_op.add_column(sa.Column("dataset_type", mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("is_latest")
        batch_op.drop_column("version_number")
        batch_op.drop_column("ds_concept_id")

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("comment"):
        op.drop_table("comment")
    if inspector.has_table("dataset_concept"):
        op.drop_table("dataset_concept")
    # ### end Alembic commands ###
