# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class Test2faa:

    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    # USER2 MUST HAVE ENABLED THE 2FA
    def test_2faa(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1440, 900)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user2@example.com")
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > .col-md-6").click()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.ID, "otp_code").click()
        # comprobamos que falla el codigo otp, porque no podemos comprobar que funcione(no podemos generarlo desde selenium)
        self.driver.find_element(By.ID, "otp_code").send_keys("026605")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestseleniumloginlimit():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testseleniumloginlimit(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(602, 743)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(6) .align-middle:nth-child(2)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("asrgwer")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("qwefqerf")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("qwefq3ef")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("qef1q3f")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("13rf13r")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("13rf13")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("3rg123rg")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("13rgf13")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("lqkwgfeuqgew")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("qwefef")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("qwrfqr")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
  
