# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class Test2faa:

    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_2faa(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1440, 900)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "email").click()
        # usamos un user que por defecto tiene activado el 2fa
        self.driver.find_element(By.ID, "email").send_keys("user3_2fa@example.com")
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > .col-md-6").click()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.ID, "otp_code").click()
        # comprobamos que falla el código OTP porque no podemos comprobar
        # que funcione (no podemos generarlo desde Selenium)
        self.driver.find_element(By.ID, "otp_code").send_keys("026605")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
