# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait


class TestTestseleniummanual:
    def setup_method(self, method):
        """Initialize Selenium driver before each test."""
        self.driver = webdriver.Firefox()
        self.driver.set_window_size(1609, 983)
        self.base_url = "http://localhost:5000"
        self.wait = WebDriverWait(self.driver, 10)

    def teardown_method(self, method):
        """Quit driver after each test."""
        self.driver.quit()

    def test_testseleniummanual(self):
        self.driver.get("http://localhost:5000/")
        self.driver.set_window_size(1609, 983)
        self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
        self.driver.find_element(By.CSS_SELECTOR, ".me-1 > polyline").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > .col-md-6").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.LINK_TEXT, "Explore").click()
        self.driver.find_element(By.NAME, "query").click()
        self.driver.find_element(By.NAME, "query").send_keys("weather")
        self.driver.find_element(By.NAME, "query").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "Clear filters").click()
        self.driver.find_element(By.NAME, "tags").click()
        self.driver.find_element(By.NAME, "tags").send_keys("major")
        self.driver.find_element(By.NAME, "tags").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "Clear filters").click()
        dropdown = self.driver.find_element(By.NAME, "publication_type")
        dropdown.find_element(By.XPATH, "//option[. = 'National']").click()
        self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
        self.driver.find_element(By.LINK_TEXT, "Clear filters").click()
        self.driver.find_element(By.NAME, "query").click()
        self.driver.find_element(By.NAME, "query").send_keys("weather")
        self.driver.find_element(By.NAME, "tags").click()
        self.driver.find_element(By.NAME, "tags").send_keys("major")
        self.driver.find_element(By.NAME, "tags").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "Clear filters").click()
        self.driver.find_element(By.ID, "filter-date-from").click()
        self.driver.find_element(By.ID, "filter-date-from").click()
        self.driver.find_element(By.NAME, "tags").click()
        self.driver.find_element(By.NAME, "tags").click()
        self.driver.find_element(By.ID, "filter-date-from").click()
        self.driver.find_element(By.ID, "filter-date-from").send_keys("2023-01-01")
        self.driver.find_element(By.ID, "filter-date-to").click()
        self.driver.find_element(By.ID, "filter-date-to").send_keys("2024-12-31")
        self.driver.find_element(By.LINK_TEXT, "Clear filters").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mb-4 option:nth-child(1)").click()
        dropdown = self.driver.find_element(By.NAME, "sort_by")
        dropdown.find_element(By.XPATH, "//option[. = 'Oldest first']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mb-4 option:nth-child(2)").click()
        self.driver.find_element(By.NAME, "query").click()
        self.driver.find_element(By.NAME, "query").send_keys("weather")
        self.driver.find_element(By.NAME, "query").send_keys(Keys.ENTER)
        dropdown = self.driver.find_element(By.NAME, "sort_by")
        dropdown.find_element(By.XPATH, "//option[. = 'Newest first']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mb-4 option:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "Clear filters").click()
        self.driver.find_element(By.NAME, "query").click()
        self.driver.find_element(By.NAME, "query").send_keys("Noexiste")
        self.driver.find_element(By.NAME, "query").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "Clear filters").click()
        self.driver.find_element(By.LINK_TEXT, "Weather Data (V2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mb-3:nth-child(12) .btn path").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mb-3:nth-child(13) path").click()
        self.driver.find_element(By.ID, "btnGroupDropExport9").click()
        self.driver.find_element(By.LINK_TEXT, "File").click()
